apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-{{.Chart.Name}}-deploy
  labels:
    app: {{.Chart.Name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
        app: nginx
        release: {{.Release.Name}}
  template:
    metadata:
      labels:
        app: nginx
        release: {{.Release.Name}}
    spec:
      containers:
      - name: {{.Values.image.name}}
        image: {{.Values.image.name}}:{{.Values.image.tag}}
        ports:
        - containerPort: {{.Values.containerPorts.http.port}}
        resources:
          requests: 
            cpu: {{.Values.resources.requests.cpu}}
            memory: {{.Values.resources.requests.memory}}
          limits: 
            cpu: {{.Values.resources.limits.cpu}}
            memory: {{.Values.resources.limits.memory}}
