apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "accessing-files.fullname" .}}
data:
{{(.Files.Glob "files/*.properties").AsConfig | indent 2 }}
{{/* {{(.Files.Glob "files/*.properties").AsSecrets | indent 2 }} */}}
