
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "templating-deep-dive.fullname" .}}-deploy
  labels: {{include "templating-deep-dive.labelSelectors" . | nindent 4}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels: 
      {{- include "templating-deep-dive.labelSelectors" . | nindent 6}}
  template:
    metadata:
      labels: 
        {{- include "templating-deep-dive.labelSelectors" . | nindent 8}}
    spec:
      containers:
      - name: {{.Values.image.name}}
        image: {{.Values.image.name}}:{{.Values.image.tag}}
        ports:
        - containerPort: {{.Values.containerPorts.http.port}}
        resources:
          requests: 
            cpu: {{.Values.resources.requests.cpu}}
            memory: {{.Values.resources.requests.memory}}
          limits: 
            cpu: {{.Values.resources.limits.cpu}}
            memory: {{.Values.resources.limits.memory}}
