apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "templating-deep-dive.fullname" .}}-deploy
  labels: {{ include "templating-deep-dive.labelSelectors" . | nindent 4}}
spec:
  replicas: {{ if eq .Values.env "production" -}}5{{- else -}}1{{- end }}
  selector:
    matchLabels: 
      {{- include "templating-deep-dive.labelSelectors" . | nindent 6}}
  template:
    metadata:
      labels: 
        {{- include "templating-deep-dive.labelSelectors" . | nindent 8}}
    spec:
      containers:
      - name: {{.Values.image.name}}
        image: {{.Values.image.name}}:{{.Values.image.tag}}
        {{- with .Values.securityContext | default dict }}
        {{- if and (hasKey . "enabled") .enabled}}
        securityContext:
          runAsUser: {{.runAsUser}}
          fsGroup: {{.fsGroup}}
        {{- end}}
        {{- end }}
        {{- if .Values.services| default dict | len }}
        ports:
        - containerPort: {{.Values.containerPorts.http.port}}
        {{- end }}
        resources:
          requests: 
            cpu: {{.Values.resources.requests.cpu}}
            memory: {{.Values.resources.requests.memory}}
          limits: 
            cpu: {{.Values.resources.limits.cpu}}
            memory: {{.Values.resources.limits.memory}}
